# Form implementation generated from reading ui file 'ui/category_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryDialog(object):
    def setupUi(self, CategoryDialog):
        CategoryDialog.setObjectName("CategoryDialog")
        CategoryDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(CategoryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=CategoryDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryNameInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.categoryNameInput.setObjectName("categoryNameInput")
        self.horizontalLayout.addWidget(self.categoryNameInput)
        self.colorButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.colorButton.setMaximumSize(QtCore.QSize(30, 30))
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout.addWidget(self.colorButton)
        self.addCategoryBtn = QtWidgets.QPushButton(parent=self.groupBox)
        self.addCategoryBtn.setObjectName("addCategoryBtn")
        self.horizontalLayout.addWidget(self.addCategoryBtn)
        self.verticalLayout.addWidget(self.groupBox)
        self.categoriesList = QtWidgets.QListWidget(parent=CategoryDialog)
        self.categoriesList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.categoriesList.setObjectName("categoriesList")
        self.verticalLayout.addWidget(self.categoriesList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editCategoryBtn = QtWidgets.QPushButton(parent=CategoryDialog)
        self.editCategoryBtn.setObjectName("editCategoryBtn")
        self.horizontalLayout_2.addWidget(self.editCategoryBtn)
        self.deleteCategoryBtn = QtWidgets.QPushButton(parent=CategoryDialog)
        self.deleteCategoryBtn.setObjectName("deleteCategoryBtn")
        self.horizontalLayout_2.addWidget(self.deleteCategoryBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.closeCategoryBtn = QtWidgets.QPushButton(parent=CategoryDialog)
        self.closeCategoryBtn.setObjectName("closeCategoryBtn")
        self.horizontalLayout_2.addWidget(self.closeCategoryBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CategoryDialog)
        QtCore.QMetaObject.connectSlotsByName(CategoryDialog)

    def retranslateUi(self, CategoryDialog):
        _translate = QtCore.QCoreApplication.translate
        CategoryDialog.setWindowTitle(_translate("CategoryDialog", "Управление категориями"))
        self.groupBox.setTitle(_translate("CategoryDialog", "Добавить категорию"))
        self.categoryNameInput.setPlaceholderText(_translate("CategoryDialog", "Название категории"))
        self.colorButton.setText(_translate("CategoryDialog", "🎨"))
        self.addCategoryBtn.setText(_translate("CategoryDialog", "Добавить"))
        self.editCategoryBtn.setText(_translate("CategoryDialog", "✏️ Редактировать"))
        self.deleteCategoryBtn.setText(_translate("CategoryDialog", "🗑️ Удалить"))
        self.closeCategoryBtn.setText(_translate("CategoryDialog", "Закрыть"))
