# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_window = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_window.setGeometry(QtCore.QRect(20, 20, 751, 551))
        self.main_window.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_window.setObjectName("main_window")
        self.btn_next = QtWidgets.QPushButton(parent=self.main_window)
        self.btn_next.setGeometry(QtCore.QRect(220, 10, 51, 23))
        self.btn_next.setObjectName("btn_next")
        self.btn_prev = QtWidgets.QPushButton(parent=self.main_window)
        self.btn_prev.setGeometry(QtCore.QRect(0, 10, 51, 23))
        self.btn_prev.setObjectName("btn_prev")
        self.widget = QtWidgets.QWidget(parent=self.main_window)
        self.widget.setGeometry(QtCore.QRect(0, 40, 751, 471))
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.main_window)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 10, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.main_window)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 10, 131, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.main_window)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 10, 131, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_date = QtWidgets.QLabel(parent=self.main_window)
        self.label_date.setGeometry(QtCore.QRect(66, 13, 141, 20))
        self.label_date.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_date.setText("")
        self.label_date.setScaledContents(False)
        self.label_date.setWordWrap(False)
        self.label_date.setObjectName("label_date")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.main_window)
        self.pushButton_6.setGeometry(QtCore.QRect(720, 10, 31, 23))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_prev, self.btn_next)
        MainWindow.setTabOrder(self.btn_next, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_next.setText(_translate("MainWindow", ">"))
        self.btn_prev.setText(_translate("MainWindow", "<"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_4.setText(_translate("MainWindow", "На неделю"))
        self.pushButton_5.setText(_translate("MainWindow", "Сегодня"))
