# Form implementation generated from reading ui file 'ui/week_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WeekDialog(object):
    def setupUi(self, WeekDialog):
        WeekDialog.setObjectName("WeekDialog")
        WeekDialog.resize(900, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(WeekDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weekLabel = QtWidgets.QLabel(parent=WeekDialog)
        self.weekLabel.setStyleSheet("font-size: 14pt; font-weight: bold; margin: 10px;")
        self.weekLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekLabel.setObjectName("weekLabel")
        self.verticalLayout.addWidget(self.weekLabel)
        self.navLayout = QtWidgets.QHBoxLayout()
        self.navLayout.setObjectName("navLayout")
        self.prevWeekBtn = QtWidgets.QPushButton(parent=WeekDialog)
        self.prevWeekBtn.setObjectName("prevWeekBtn")
        self.navLayout.addWidget(self.prevWeekBtn)
        self.closeBtn = QtWidgets.QPushButton(parent=WeekDialog)
        self.closeBtn.setObjectName("closeBtn")
        self.navLayout.addWidget(self.closeBtn)
        self.nextWeekBtn = QtWidgets.QPushButton(parent=WeekDialog)
        self.nextWeekBtn.setObjectName("nextWeekBtn")
        self.navLayout.addWidget(self.nextWeekBtn)
        self.verticalLayout.addLayout(self.navLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=WeekDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 880, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.weekLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.weekLayout.setObjectName("weekLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(WeekDialog)
        QtCore.QMetaObject.connectSlotsByName(WeekDialog)

    def retranslateUi(self, WeekDialog):
        _translate = QtCore.QCoreApplication.translate
        WeekDialog.setWindowTitle(_translate("WeekDialog", "Задачи на неделю"))
        self.weekLabel.setText(_translate("WeekDialog", "Неделя: 01.01.2024 - 07.01.2024"))
        self.prevWeekBtn.setText(_translate("WeekDialog", "← Предыдущая неделя"))
        self.closeBtn.setText(_translate("WeekDialog", "Закрыть"))
        self.nextWeekBtn.setText(_translate("WeekDialog", "Следующая неделя →"))
